### ISSUE TITLE
Idea: Responsive Gutters

### ISSUE THREAD

**Issue by andycochran** [zurb/foundation-sites-6#161]
A specific gutter width can work well on small devices, but be too cramped on large devices (and vice versa)—e.g. on a large screen two columns of text are too close to each other to be legible. Could we perhaps define gutters per break point?

**Comment by erutan** [comment]
I personally like how singularity.gs handles this (in Foundation 5 I'd use it and breakpoint instead of the default grids): https://github.com/at-import/Singularity/wiki/Creating-Grids#responsive-grids

It definitely makes sense to have different gutters at different breakpoints (and it's not too far a push from there to just define a new grid system if you're using sass includes).

**Comment by gakimball** [comment]
We started working on responsive gutters, but they weren't finished in time for the launch, so they're being pushed to 6.1. The feature is on our internal roadmap, so you'll see it soon :)

**Comment by andycochran** [comment]
Nice! Y'all rock.

**Comment by LukePettway** [comment]
Glad to hear it, looking forward to the awesomeness that they will be.
