### ISSUE TITLE
Feedback: JavaScript usage

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites-6#19]
We've made a few fundamental changes to how the JavaScript is structured, which we'd like the community's feedback on.

**All plugins are classes.** This allows them to be initialized and manipulated programmatically.

```js
var $elem = $('#modal');
var modal = new Foundation.Reveal($elem, {
  overlay: false,
  fullscreen: true
});
```

**Individual options can be added as data attributes.** `data-options` will still be available also.

```html
<div class="reveal" data-reveal data-overlay="false"></div>
```

**(Most) plugins don't generate markup.** This makes plugins easier to reform with HTML, and cuts down on the number of plugin options that are just for changing elements. Orbit is a good example—it doesn't generate any HTML, which means if you don't want a piece of it, you just remove it from the markup.

```html
<div class="orbit" data-orbit>
  <ul class="orbit-container">
    <button class="orbit-control orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
    <button class="orbit-control orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
    <li class="active">
      <img class="orbit-image" src="http://placecage.com/800/500" alt="Intropsective Cage">
      <figcaption class="orbit-caption">Woah. Nicolas Cage.</figcaption>
    </li>
    <li>
      <img class="orbit-image" src="http://placecage.com/800/500" alt="Intropsective Cage">
      <figcaption class="orbit-caption">Woah. Nicolas Cage.</figcaption>
    </li>
  </ul>
  <nav class="orbit-bullets-container">
    <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
    <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
  </nav>
</div>
```

**Comment by rmartin** [comment]
hey @gakimball , 

First of all, thanks for all of your and the teams hard work on F6. There are a lot of great additions, including the new proposal for the plug-in architecture. Overall i think this is a good idea and I had a chance to review the code to get a better sense for how you're keeping track of the various instances of the plugins and registering those within the namespace. 

One topic I wanted to bring up for discussion was the class style implementation. Have you considered potentially implementing the OLOO style as an alternative to the class approach? Looking through the code specifically with the reveal plugin, it doesn't appear that it's really leveraging any inheritance structure and that the 'class' implementation is more of a namespacing solution to encapsulate the instance of that plug-in. It also appears to cause a fair amount of extra work to encapsulate the this keyword in the correct scope which is adding some additional code and challenges making the various methods public / private. 

It would seem that if we were to leverage a style similar to the OLOO style, it would be able to eliminate the 'new' prefix requirement and also greatly simplify the internal organization of the private / public methods. So instead of needing to setup all the methods as a prototype we'd be able to simply structure those methods separately and simply create the object on the fly. 

Is that something that you've considered or think might be a worthwhile addition to explore? I know that feedback such as 'you should do X instead of Y' isn't very constructive. However, if this approach is something you'd be interested in exploring I'd be happy to work together to see how this style might work by refactoring one of the plug-ins. 

References:
* [You Don't Know JS - This & Object Prototypes](https://github.com/getify/You-Dont-Know-JS/blob/8fcecaea1a0805fc2e10fd44f6980a85a63a2ab8/this%20%26%20object%20prototypes/ch6.md)
* [OLOO vs Prototype Design Pattern](http://stackoverflow.com/a/30468602)
* [JavaScript Pattern Comparison - John Dugan](https://john-dugan.com/object-oriented-javascript-pattern-comparison/)

Cheers,
Roy

**Comment by gakimball** [comment]
@rmartin I'll see if @zurbchris wants to chime in on this.

We definitely can't re-architect everything right now. I will say we have ES6 in the back of our heads, at which point we'd be converting these function-based classes to ES6 classes. Since we'd have to make the switch after version 6.0.0 comes out, that would be the easiest way to keep everything backwards-compatible.

**Comment by zurbrandon** [comment]
Thanks for all the feedback, everyone! The team has went over all these discussion topics and have either incorporated the feedback, have a plan to incorporate I or decided to not include it. 

We'll close these topics, but feel free to keep adding and discussing if you'd like.
