### ISSUE TITLE
NoMethodError: undefined method `specificity' for &:Sass::Selector::Parent 

### ISSUE THREAD

**Issue by qantumthemes** [zurb/foundation-sites-6#247]
When adding the foundation-media-object scss I get the error:
NoMethodError: undefined method `specificity' for &:Sass::Selector::Parent 

I'm compiling scss with codekit (if someone knows about compatibility issues).
Thanks!

**Comment by gakimball** [comment]
See if you can figure out which version of Ruby Sass you're compiling with. It should be 3.4.

**Comment by gakimball** [comment]
Haven't heard back yet so I'm going to close this out. We've moved development back to the main Foundation repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites), so please report any future issues there.

Because it's a Sass compiler error, this might be a CodeKit issue, so if you're still having problems you can also ask in the [CodeKit issue tracker](https://github.com/bdkjones/CodeKit/issues).

Lastly, CodeKit has official support for Foundation 6 now, as of [version 2.6.1](https://incident57.com/codekit/versionhistory.html).
