### ISSUE TITLE
[Installation] bower install foundation-sites fails

### ISSUE THREAD

**Issue by fulup-bzh** [zurb/foundation-sites-6#248]
**How can we reproduce this bug?**

1. Step one "cut & paste installation command from web page"
  bower install foundation-sites

**What did you expect to happen?**
  bower ENOTFOUND     Package foundation-sites not found

Note: using NPM it works

**Comment by joepurdy** [comment]
I double checked with the bower package registry ( http://bower.io/search/?q=foundation-sites ) and it doesn't appear the foundation-sites package is published yet. This will likely be the case until the first release candidate.

**Comment by fulup-bzh** [comment]
It is not a big error, nevertheless it's probably not a good idea to leave on your main documentation, command that do not work.

**Comment by gakimball** [comment]
We aren't publishing to Bower yet because the Git repo we need to point to is zurb/foundation-sites, not zurb/foundation-sites-6. (When 6 launches, we're renaming zurb/foundation to zurb/foundation-sites.) npm is easier to publish to because it doesn't use Git for version management.

The docs are going to have some temporary inaccuracies while we get all of our ducks in a row, but the launch of 6 is pretty close.
