### ISSUE TITLE
Error Installing the NPM Package

### ISSUE THREAD

**Issue by shawnrice** [zurb/foundation-sites-6#291]
I'm not sure if this is something that just crept up, but the install for the npm package seems to be broken.

Here's a gist with the error logs (including the entire npm-debug.log): https://gist.github.com/shawnrice/3d57bd47f6e7c6968224

It seems like one fail point is when trying to install the particular paint-by-number module, but there are a couple of others.

**Comment by aibrean** [comment]
I did a CLI install 2 days ago without issues.

**Comment by gakimball** [comment]
Could be a Node 5 issue, I'll look into it.

**Comment by gakimball** [comment]
Okay, there's two errors in here. When you installed `foundation-cli`, you got a network timeout, and it doesn't look like the CLI installed at all. For that I would just try installing again, and see if you get the same exact network error.

The second command you run is `npm update` inside of the Foundation 6 repo, which will attempt to update your dependencies for Foundation 6. So that part isn't related to the CLI at all.

It's worth noting that you're using Node 5 and NPM 3, but not all Node libraries have been updated to be cross-compatible with NPM 2 and 3, so I think some of the errors come from there as well.

**Comment by gakimball** [comment]
We're working on closing out this repo so we can move back to the main Foundation repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). I explained above what I think the source of those two issues are. We also published a final 2.0.0 version of the CLI last week, so I'd recommend installing it and seeing what happens.
