### ISSUE TITLE
Forms - Styling 

### ISSUE THREAD

**Issue by blynnc** [zurb/foundation-sites-6#306]
I am playing around with forms.  I like to color certain form types.
Especially the SELECT to match my layout colors. 

I'm trying via CSS. I'm doing rather well altering the foundation.css via app.css
I can get pretty close  to everything I need with  all the css under 

select{}   

select:focus {
    background-color: #e8caaa;
    border-color: #de6315; 
	}
	
select>option{ 
color: #000000 !important; 
padding:0.3rem;

QUESTION: with css how do I do the option rollover color ?
}

**Comment by blynnc** [comment]
Thanks.  I gathered that after I tried to do cross browser "look Ma, no jquery or plugins" for a while. I'll try your suggestion.

**Comment by blynnc** [comment]
I'm also going to try Foundation 6's nice features - Drop Down Menu and Drop Down Buttons to do what I want color wize.

**Comment by gakimball** [comment]
There's no built-in option for a `<select>` hover state, but they're very easy to add:

```css
select:hover {
  background-color: #ccc;
  border-color: #999;
}
```

As for custom dropdown styles, as @JeremyEnglert alluded to, you can't style the dropdown itself, because your computer's OS decides what it looks like. The last jQuery select plugin I used was [Selectric](http://lcdsantos.github.io/jQuery-Selectric/), and it was relatively painless to get working.
