### ISSUE TITLE
Global Spacing Mixin

### ISSUE THREAD

**Issue by CGTS** [zurb/foundation-sites-6#318]
Are there plans to include a global spacing mixin along the lines of https://github.com/jptaranto/typey/tree/master/stylesheets/typey/mixins

Once we define the base line height, let's say `24px` we could then add:

`@include margin(1);`  (margin could just as easily be padding or margin-top etc..)

This would produce `margin: 24px; margin: 1rem;` using `@include padding-top(1.5)` would produce `padding-top: 36px; padding-top 1.5rem' etc... 

I've found these spacing mixins to be really helpful in maintaining a consistency as well as producing px units for older browsers if needed.

**Comment by gakimball** [comment]
Since we don't support any browsers that don't support `rem`, we don't have any need for mixins that produce these fallbacks.

However, you could use the PostCSS plugin [pixrem](https://github.com/robwierzbowski/node-pixrem) to generate the fallback for you. If you use Grunt or Gulp, you can load in `grunt-postcss` or `grunt-postcss` and then `pixrem` to create the `px` versions of the values.
