### ISSUE TITLE
Docs js error

### ISSUE THREAD

**Issue by designerno1** [zurb/foundation-sites-6#325]
i got 2 js errors in the docs
```js
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
function listeningElementsMutation(mutationRecordsList) {
http://localhost:3000/assets/js/foundation.js
Line 1573
```
and
```js
ReferenceError: Foundation is not defined
new Foundation.Magellan($toc, {});
http://localhost:3000/assets/js/docs.js
Line 5220
```

**Comment by gakimball** [comment]
Fixed with [this commit](https://github.com/zurb/foundation-sites/commit/7c8ad6780cbb6874c908bd5f490702253b9bda25#diff-511816183c2a107169e060017bed2d8f).

Now that Foundation 6 is out, development has moved back to the main repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites). So you can open any future issues there.
