### ISSUE TITLE
Show / Hide for classes have wrong breakpoints

### ISSUE THREAD

**Issue by CreativeLittleChris** [zurb/foundation-sites-6#337]
The default breakpoint for small is anything below 40rem, however show-for-small-only is not set to this.

Other breakpoints for show/hide classes also appear to be incorrect. See attachment.
![screen shot 2015-11-21 at 16 45 31](https://cloud.githubusercontent.com/assets/10211530/11319455/9f259974-906f-11e5-9648-40a7c3991435.png)

**Comment by gakimball** [comment]
We made a last-minute change to the `medium` breakpoint—we tried moving it down to 512px, but ended up putting it back at 640px. I think when the initial templates shipped they had a slightly out-of-date settings file, so that's our bad.

If you open your settings file and find the `$breakpoints` variable, `medium` might still be set to `512` for you, which is why all of your breakpoints hover around `32em` instead of `40em`.

**Comment by gakimball** [comment]
Just updated the settings files for both templates so they're up-to-date with Foundation 6.0.3.

**Comment by gakimball** [comment]
Going to close this out, as I believe the reason you're seeing a `32em` breakpoint is because the pixel value defined in your settings file is `512px`. If you bump it up to `640px`, you'll see `40em` again.

If you encounter any more issues with breakpoints, or anything else, open a new issue on the main Foundation repo, [zurb/foundation-sites](https://github.com/zurb/foundation-sites), as this one will be closing in the next week. Thanks! :)
